### PR TITLE
Update Manifest

### PR DESCRIPTION
**Pull request by 1Dimitri**
properly load assembly (avoiding "avoid Unable to find type [Security.Cryptography.ProtectedData]" error
Test-ModuleManifest should not output error 
cf. CompatiblePSEditions in  https://docs.microsoft.com/en-us/powershell/gallery/concepts/module-psedition-support

### CODE REVIEW

**Comment by beatcracker** [comment]
Hi there, thanks for sharing your work!

Did you had issues with loading `System.Security` assembly when using non-array notation? I'd like to try to reproduce that.

I'm also not sure about updating `PowerShellVersion` to `5.1`. My intention for this module was to be very simple and downlevel compatible. Looks like specifying `CompatiblePSEditions` was a mistake from the start, since [docs](https://docs.microsoft.com/en-us/powershell/gallery/concepts/module-psedition-support) state that 

> Once a module manifest is specified with the `CompatiblePSEditions` key or uses `$PSEdition` variable, it can not be imported on lower versions of PowerShell.

Maybe it should be dropped altogether.  It probably worked for me since `-Version 3` [does nothing](https://stackoverflow.com/a/44457275/4424236).

**Comment by 1Dimitri** [comment]
I've tested the module under Windows 2012 R2 (Updated to WMF 5.1) and Windows 2016.
In both cases, RequiredAssemblies with a single string makes the functions to be imported when running Import-Module, but fail at execution time as they are not able to use [Security.Cryptography.ProtectedData]. Import-Module and manual Add-Type -AssemblyName System.Security solves the issue so there's a assembly issue
For the PS Version, it's your call, but I'm not sure you can get away not to specify Desktop when running under 5.1,  I've not tested that scenario

**Comment by beatcracker** [comment]
Thanks, sorry for delays!

**Comment by 1Dimitri** [comment]
Thanks for all of us behind a firewall for the module BTW :-)

**Pull request merged**
